### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by FishHawk** [FishHawk/lisu#1]
### 1.0milestone:

- [ ] 章节连续？至少实现章节状态
- [ ] preload失败后会一直尝试获取
- [ ] 让订阅更新周期可以设置(本质是config) 保存cookies
- [ ] 漫画人500错误，很神秘
- [ ] 中文翻译

### Reader

- [ ] 混叠
- [ ] 边缘剪裁（固定式）（理论上很简单，高优先级）
- [ ] 分页

### Webtoon Reader

- [ ] zoom，需要重写LazyColumn，有办法用internal了
- [ ] Side Padding

### 等待report：

- [ ] app action button间距太大了
- [ ] app action会填满整个row

### 低优先级：
- [ ] Web 客户端
- [ ] provider base filter 折叠
- [ ] 切换主题时，toolbar和content颜色不同时改变
- [ ] BottomNavigation 折叠动画不会改变高度
- [ ] BottomNavigation too big
- [ ] history分页？
- [ ] refresh
- [ ] request next page还能再优化一下？
- [ ] 有必要在gallery实现real time的下载进度吗？
- [ ] share element，动画升级 https://fornewid.medium.com/material-motion-for-jetpack-compose-d97ef2114b9c
- [ ] tooltip
- [ ] language？
- [ ] bug：ExposedDropdownMenuBox有点问题
- [ ] 设计 view state
- [ ] 设计 more
- [ ] 迁移？
- [ ] boardModel后端翻译
- [ ] ehentai标签前端翻译
- [ ] 二维码登录
